// apps/workbench/src/components/ResponsiveRail.tsx
import { useEffect, useState, useSyncExternalStore, type ReactNode } from "react";
import { PanelRightOpen } from "lucide-react";
import AppDialog from "./AppDialog";
import { dialogCount, subscribeDialogStack } from "../lib/dialogStack";

export default function ResponsiveRail({ label, title, children }: { label: string; title: string; children: ReactNode }) {
  const [drawerOpen, setDrawerOpen] = useState(false);
  const openDialogs = useSyncExternalStore(subscribeDialogStack, dialogCount);
  useEffect(() => { if (drawerOpen && openDialogs > 1) setDrawerOpen(false); }, [drawerOpen, openDialogs]);
  return <>
    <aside className="review-rail desktop-rail" aria-label={title}>{children}</aside>
    <button className="rail-trigger secondary-button" type="button" data-testid="rail-trigger" onClick={() => setDrawerOpen(true)}><PanelRightOpen aria-hidden="true" />{label}</button>
    <AppDialog open={drawerOpen} title={title} variant="drawer" onClose={() => setDrawerOpen(false)}>{children}</AppDialog>
  </>;
}

// docs/development/archive/m02-vue-workbench-baseline/src/components/ResponsiveRail.vue
<script setup lang="ts">
import { ref, watch } from "vue";
import { PanelRightOpen } from "lucide-vue-next";
import AppDialog from "./AppDialog.vue";
import { dialogStack } from "../lib/dialogStack";

defineProps<{
  label: string;
  title: string;
}>();

const drawerOpen = ref(false);

watch(dialogStack, (stack) => {
  // 抽屉之上又打开了来源详情或草稿确认等对话框时，先关闭抽屉，避免两个浮层叠加。
  if (drawerOpen.value && stack.length > 1) {
    drawerOpen.value = false;
  }
});
</script>

<template>
  <aside class="review-rail desktop-rail" :aria-label="title">
    <slot />
  </aside>
  <button class="rail-trigger secondary-button" type="button" data-testid="rail-trigger" @click="drawerOpen = true">
    <PanelRightOpen aria-hidden="true" />
    {{ label }}
  </button>
  <AppDialog v-model="drawerOpen" :title="title" variant="drawer">
    <slot />
  </AppDialog>
</template>
